---
# The instance types used for almost all the instances expose EBS
# volumes as NVMe block devices, so that's why we need nvme here.
- hosts: all
  name: Install NVMe support, add banner, persist journald, and install ClamAV
  become: yes
  become_method: sudo
  roles:
    - nvme
    - banner
    - persist_journald
    - clamav

# The bastion should have as little installed as possible, since it's
# exposed to the cruel world
- hosts: all:!bastion
  name: Install htop
  become: yes
  become_method: sudo
  roles:
    - htop

- hosts: nmap
  name: Install nmap
  become: yes
  become_method: sudo
  roles:
    - cyhy_runner
    - nmap
    - more_ephemeral_ports

- hosts: mongo
  name: Install and configure MongoDB and xfsprogs
  become: yes
  become_method: sudo
  roles:
    - xfs
    - mongo
    - cyhy_feeds

- hosts: nessus
  name: Install and configure Nessus
  become: yes
  become_method: sudo
  roles:
    - cyhy_runner
    - {role: nessus, package_bucket: ncats-3rd-party-packages}
    - more_ephemeral_ports

- hosts: bod
  name: Configure host for BOD 18-01 scanning and reporting
  become: yes
  become_method: sudo
  roles:
    - xfs
    - orchestrator
    - vdp_scanner
    - cyhy_mailer

- hosts: code_gov
  name: Configure host for code.gov updating
  become: yes
  become_method: sudo
  roles:
    - code_gov_update

- hosts: client_cert
  name: Configure host for client cert auth updating
  become: yes
  become_method: sudo
  roles:
    - client_cert_update

- hosts: cyhy_commander
  name: Install and configure cyhy-commander
  become: yes
  become_method: sudo
  roles:
    - cyhy_commander

- hosts: cyhy_reporter
  name: Install and configure cyhy-reports
  become: yes
  become_method: sudo
  roles:
    - xfs
    - cyhy_reports
    - cyhy_mailer

- hosts: cyhy_dashboard
  name: Install and configure cyhy-dashboard
  become: yes
  become_method: sudo
  roles:
    - ncats_webd
    - ncats_webui
    - docker

- hosts: cyhy_archive
  name: Install cyhy-archive helper script
  become: yes
  become_method: sudo
  roles:
    - cyhy_archive
