---
- hosts: localhost
  gather_facts: yes
  check_mode: no
  tasks:
    - name: Add public ip addresses to an dynamic inventory
      add_host:
        name: "{{ host }}"
        groups: "{{ host_groups.split(',') }}"

    - wait_for:
        port: 22
        host: "{{ host }}"
        search_regex: OpenSSH
      delegate_to: "{{ bastion_host }}"
      when: bastion_host is defined

    - wait_for:
        port: 22
        host: "{{ host }}"
        search_regex: OpenSSH
      when: bastion_host is not defined

- hosts: all
  name: Configure groups now that cloud-init has run
  become: yes
  become_method: sudo
  roles:
    - groups

- hosts: mongo
  name: Configure MongoDB
  become: yes
  become_method: sudo
  roles:
    - mongo
    - mongo_logrotate
    - cyhy_feeds

- hosts: pnnl
  name: Finalize cyhy_feeds setup
  become: yes
  become_method: sudo
  roles:
    - cyhy_feeds

- hosts: bod_docker
  name: Configure Docker hosts for BOD 18-01 scanning and reporting
  become: yes
  become_method: sudo
  roles:
    - orchestrator
    - cyhy_mailer
    - code_gov_update
    - client_cert_update

- hosts: cyhy_commander
  name: Configure cyhy-commander hosts
  become: yes
  become_method: sudo
  roles:
    - cyhy_commander
    - {role: swap, swapfile_size: 2GiB}
    - cyhy_logrotate

- hosts: nmap
  name: Configure nmap scanning hosts
  become: yes
  become_method: sudo
  roles:
    - { role: swap, swapfile_size: 2GiB}

- hosts: cyhy_runner
  name: Configure cyhy-runner hosts
  become: yes
  become_method: sudo
  roles:
    - chown_cyhy_dirs
    - cyhy_logrotate

- hosts: nessus
  name: Configure Nessus hosts
  become: yes
  become_method: sudo
  roles:
    - nessus

- hosts: cyhy_reporter
  name: Configure cyhy-reports hosts
  become: yes
  become_method: sudo
  roles:
    - cyhy_reporter
    - cyhy_logrotate
    - cyhy_mailer

- hosts: cyhy_bastion
  name: Configure cyhy bastion hosts
  become: yes
  become_method: sudo
  roles:
    - cyhy_ops

- hosts: cyhy_dashboard
  name: Install and configure cyhy-dashboard
  become: yes
  become_method: sudo
  roles:
    - cyhy_dashboard

- hosts: cyhy_archive
  name: Configure cyhy-archive hosts
  become: yes
  become_method: sudo
  roles:
    - cyhy_archive

- hosts: mgmt_bastion
  name: Configure management bastion hosts
  become: yes
  become_method: sudo
  roles:
    - mgmt_ops
